from __future__ import annotations
from typing import Protocol


class IChatClient(Protocol):
    async def create_chat(self, *, channel_id: str, organizer_id: str, client_id: str) -> None: ...

    async def delete_chat(self, *, channel_id: str) -> None: ...

    def create_token(self, *, user_id: str, name: str, expires_at: int) -> str: ...


class IChatController(Protocol):
    async def create_chat(self, *, channel_id: str, organizer_id: str, client_id: str) -> None: ...

    async def delete_chat(self, *, channel_id: str) -> None: ...

    def create_token(self, *, user_id: str, name: str, expires_at: int) -> str: ...
